sudo: true 
os: osx
osx_image: xcode10.2
language: C
compiler: clang
env:
 - PG_TEST_EXTRA=kerberos
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bison flex; fi

install:
- yes | sudo perl -MCPAN -e 'install DBI'

script:
- echo $TRAVIS_OS_NAME
- gcc --version
- wget https://buildfarm.postgresql.org/downloads/latest-client.tgz
- tar -xzvf latest-client.tgz
- perl ./build-farm-10/run_build.pl --nosend --nostatus --verbose=2
