sudo: true 
os: macos
osx_image: xcode10.2
language: perl
compiler: clang
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install bison flex; fi

install:
- which perl
- cpanm  Bundle::LWP

script:
- wget https://buildfarm.postgresql.org/downloads/latest-client.tgz
- tar -xzvf latest-client.tgz
- cd build-farm-10
- perl run_build.pl
